### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by worlddada** [RealQuestions/firstslip#3]
Need to fix the homepage new design to be more usable and data needs to flow better.

**Comment by erlepereira** [comment]
Let break this down into specifics and prioritize. Leaving this open, until we add the specific listings on, then we can reference to them & close this issue.

**Comment by erlepereira** [comment]
New v2 engine, designed to be capable enough to incorporate needed flexibility.
Moving to version 2 of site. This is closed.
