### ISSUE TITLE
Author and supporters of each question should be advised when an email is sent to a politician

### ISSUE THREAD

**Issue by cejago** [RealQuestions/firstslip#6]
Currently, politicians are advised by email when a question reaches the target level of support. However, there is currently no notice to the author or those supporting the question when that email is sent. 

Therefore new emails needed to be added to: a) the author and b) the supporters that the email has been emailed to the politician.

Contact me for the text of the email to be used.

**Comment by erlepereira** [comment]
To be incorporated & evaluated in v2.
Moving to version 2 of site. This is closed.
